mysite/chatapp/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views

app_name = 'chatapp'

urlpatterns = [
    path('', views.index,name='index'),
    path('<slug:slug>/',views.chatroom,name='chatroom'),
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rooms/',include('chatapp.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authentication_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
]

mysite/chatapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class ChatRoom(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(unique=True)

class ChatMessage(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(ChatRoom,on_delete=models.CASCADE)
    message_content = models.TextField()
    date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('date',) 

    

mysite/users/models.py
from django.db import models

# Create your models here.

mysite/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

mysite/chatapp/views.py
from django.shortcuts import render
from .models import ChatRoom,ChatMessage

# Create your views here.
def index(request):
    chatrooms = ChatRoom.objects.all()
    return render(request,'chatapp/index.html',{'chatrooms':chatrooms})

def chatroom(request,slug):
    chatroom = ChatRoom.objects.get(slug=slug)
    messages = ChatMessage.objects.filter(room=chatroom)[0:30]
    return render(request,'chatapp/room.html',{'chatroom':chatroom,'messages':messages})

mysite/users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm

# Create your views here.
def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST) 
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username},Your account is created.')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'users/register.html', {'form': form})

mysite/chatapp/templates/chatapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
    crossorigin="anonymous"></script>
  <title>Document</title>
</head>

<body>

  <nav class="navbar bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img
          src="https://cdn2.iconfinder.com/data/icons/knowledge-promotion-3/64/Paper_Plane_message_publish_craft_fold_communications-256.png"
          alt="Logo" width="50" height="30" class="d-inline-block align-text-top">
        Chat App
      </a>
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <a class="nav-link active" href="{% url 'chatapp:index' %}">Rooms</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
            <a class="nav-link" href="{% url 'login' %}">Login</a>

          {% endif %}
        </li>


      </ul>

    </div>
  </nav>
  <!-- {% if messages %}
      {% for message in messages %}
        {{ message }}
      {% endfor %}
    {% endif%} -->

  {% block body %}
  {% endblock %}

</body>

</html>

mysite/chatapp/templates/chatapp/index.html
{% extends 'chatapp/base.html' %}
{% block body %}
<h1 class="font-bold m-10 m-3" >List of Rooms</h1>
{% for chatroom in chatrooms %}
    <div class="shadow-lg p-3 mb-5 bg-dark rounded text-danger">
        <a href="{% url 'chatapp:chatroom' chatroom.slug %}">{{ chatroom.name }}</a></br>

    </div>
    
    
{% endfor %}
{% endblock %}

mysite/chatapp/templates/chatapp/room.html
{% extends 'chatapp/base.html' %}
{% block body %}
<div class="m-10 font-bold" style="font-size: 200%; ">
    {{chatroom.name}}

</div>

<div class="message-container m-5  " id="message-container  " style=" overflow:scroll ;max-height:700px; max-width:650px ; ">
    <div id="chat-mesaages">
        {% for message in messages %}
        <div class="message shadow-lg rounded p-1 m-1 w-1/2 bg-info">
            <div class="text-sm text-muted">
                {{ message.user.username }}
            </div >
                {{ message.message_content }}
            <div class="text-sm text-muted">
                {{ message.date }}
    
            </div>
    
        </div>
        {% endfor %}
    </div>
</div>

         
    

<div class="form-container fixed-bottom p-2 bg-dark">
    <form method="post">
        <input class="rounded-md px-2" id="message-input" type="text" name="message" placeholder="Enter message">
        <button class="tex-white ml-5" id="send-button" type="submit">Send</button>
    </form>
</div>

{{ chatroom.slug|json_script:"json-chatroomname" }}
{{ request.user.username|json_script:"json-username" }}
<script>
    const chatRoomName=JSON.parse(document.getElementById('json-chatroomname').textContent)
    const username = JSON.parse(document.getElementById('json-username').textContent)
    const chatSocket = new WebSocket(
        'ws://'
        +window.location.host
        +'/ws/'
        +chatRoomName
        +'/'
    )
    // console.log(chatSocket)
    chatSocket.onmessage = function(e){
        // console.log("This is a message")
        const data = JSON.parse(e.data)
        if(data.message){
            console.log('Received message to client is',data.message)
            // Displaying message on Browser
            let html = '<div class="message shadow-lg rounded p-1 m-1 w-1/2 bg-info">' +
                       '<div class="text-sm text-muted">' +
                        data.username + ' </div> ' + data.message + '<div class="text-sm text-muted">'+'Now' + ' </div>'
            if(document.getElementById('chat-messages') != null){
                document.getElementById('chat-messages').innerHTML += html
                scroll()
            }
            
        }else{
            alert('The message was empty')
        }


    }
    chatSocket.onclose = function(e){
        console.log("Socket closed")
    }

    document.getElementById('send-button').onclick = function(e){
        e.preventDefault()
        const messageInput = document.getElementById('message-input')
        const message = messageInput.value
        console.log(message)
        
        chatSocket.send(JSON.stringify({
            'message': message,
            'username': username,
            'room': chatRoomName

        }))
        messageInput.value = ''
    }

    function scroll(){
        const mcontainer = document.getElementById('message-container')
        mcontaner.scrollTop = mcontainer.scrollHeight
    }

    scroll()
</script>
{% endblock %}

mysite/users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

mysite/users/templates/users/logout.html
<h1>You have been logged out</h1>

mysite/users/templates/users/register.html
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Signup</button>

</form>